# Evita 404 al refrescar
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy de API (Netlify → tu VPS)
[[redirects]]
  from = "/api/*"
  to = "http://134.199.195.151/api/:splat"
  status = 200
  force = true
