[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  functions = "no-functions-here" # ruta inexistente para desactivar

# SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API
[[redirects]]
  from = "/api/*"
  to = "http://134.199.195.151/api/:splat"
  status = 200
  force = true
