# SPA: evita 404 al refrescar
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy de API: Netlify (HTTPS) -> VPS (HTTP)
[[redirects]]
  from = "/api/*"
  to = "http://134.199.195.151/api/:splat"
  status = 200
  force = true
